webtalk_init -webtalk_dir C:/Users/eayal/OneDrive/Desktop/CS_M152A_Labs/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/clock_dividerTB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov  9 17:55:00 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212940471_0_0_405" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "406bcce8-b9f5-48c5-a4f4-54b2c6b343f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "92cd373c3efa417db1b87305ac5a7ad1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "179" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 s" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "108.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16172_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4001115270 -regid "212940471_0_0_405" -xml C:/Users/eayal/OneDrive/Desktop/CS_M152A_Labs/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/clock_dividerTB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/eayal/OneDrive/Desktop/CS_M152A_Labs/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/clock_dividerTB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/eayal/OneDrive/Desktop/CS_M152A_Labs/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/clock_dividerTB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
